apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n
  labels:
    app: n8n
    component: configmap
data:
  NODE_ENV: "development"
  GENERIC_TIMEZONE: "Europe/Lisbon"
  # Database configurations
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "app"
  DB_POSTGRESDB_DATABASE: "app"
  DB_POSTGRESDB_HOST: "my-cluster-rw.databases"
  DB_POSTGRESDB_PORT: "5432"
  # Turn on basic auth
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
