apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
    - name: audiobookshelf
      port: 13378
      targetPort: 80

  selector:
    app: audiobookshelf
  type: ClusterIP
