apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
    - name: audiobookshelf
      port: 3005
      targetPort: 3005

  selector:
    app: audiobookshelf
  type: ClusterIP
