apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    additionalPrometheusRulesMap:
      example-rule:
        groups:
          - name: example-alerting-rules
            rules:
              - alert: HighCPUUsage
                expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 30
                for: 1m
                labels:
                  severity: warning
                annotations:
                  summary: "High CPU usage on {{ $labels.instance }}"
                  description: "CPU usage is above 30% for more than 1 minute."

    grafana:
      enabled: true
      adminPassword: "admin"
      ingressClassName: traefik
      ingress:
        enabled: true
        pathType: Prefix
        path: /
        tls:
          - secretName: grafana-tls-secret
            hosts:
              - grafana.mydomain.com
        hosts:
          - grafana.mydomain.com
